services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=shot-api
    volumes:
      - "${HOME}/docker-compose/data/mysql/data:/var/lib/mysql"
      - "${HOME}/docker-compose/data/mysql/config:/etc/mysql/conf.d"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 256M
    networks:
      - local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-standalone:
    restart: always
    image: redis:7.0
    container_name: redis-standalone
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 32M
        reservations:
          cpus: "0.1"
          memory: 32M
    ports:
      - "6379:6379"
    networks:
      - local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  local:
    driver: bridge
