version: "3.9"
services:
  shop-api:
    restart: always
    image: shop-api
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 256M
    ports:
      - "8080:8080"
    network_mode: "host"
