// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	null "github.com/guregu/null/v5"
	"github.com/shopspring/decimal"
)

type Product struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	CategoryID  int64           `json:"category_id"`
	Price       decimal.Decimal `json:"price"`
	// 推薦排序
	Rank      int        `json:"rank"`
	CreatedAt int64      `json:"created_at"`
	UpdatedAt null.Int64 `json:"updated_at"`
}

type Token struct {
	ID           int64      `json:"id"`
	UserID       int64      `json:"user_id"`
	DeviceID     string     `json:"device_id"`
	RefreshToken string     `json:"refresh_token"`
	CreatedAt    int64      `json:"created_at"`
	UpdatedAt    null.Int64 `json:"updated_at"`
	ExpiredAt    int64      `json:"expired_at"`
}

type User struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	// SHA-256 加密後的密碼
	Password  string     `json:"password"`
	CreatedAt int64      `json:"created_at"`
	UpdatedAt null.Int64 `json:"updated_at"`
	DeletedAt null.Int64 `json:"deleted_at"`
}

type UserCategoryPreference struct {
	ID         int64      `json:"id"`
	UserID     int64      `json:"user_id"`
	CategoryID int64      `json:"category_id"`
	CreatedAt  int64      `json:"created_at"`
	UpdatedAt  null.Int64 `json:"updated_at"`
}
