// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_category_perference.sql

package query

import (
	"context"
)

const getUserCategoryPreferenceByUserID = `-- name: GetUserCategoryPreferenceByUserID :one
SELECT ` + "`" + `category_id` + "`" + ` FROM ` + "`" + `user_category_preference` + "`" + ` WHERE ` + "`" + `user_id` + "`" + ` = ? LIMIT 1
`

func (q *Queries) GetUserCategoryPreferenceByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCategoryPreferenceByUserID, userID)
	var category_id int64
	err := row.Scan(&category_id)
	return category_id, err
}
